swt:
  level: 7 #int
  swt_frame_length: 2 # int in seconds
  swt_hop_ratio: 0.5 #float
  axis: -1 # int
  k: 1.4826 #float
  wavelet: "db8" #str
  t_mode: "sure" #str
  t_meth: "soft" #str , hard or garotte?
  percentile: 80

mlp:
  random_state: 42
  test_size: 0.2
  model_dir_out: "C:/Users/luede/Documents/Github/whaledetection/models/mlp"
  epochs: 50
  patience: 8
  dropout: 0.2
  hidden_1: 512
  hidden_2: 256
  hidden_3: 128
  hidden_4: 64
  batch_size: 128
  learning_rate: 0.001


denoise:
  method: "none"
pad:
  pad_mode: "reflect" #str
  
loadSignal:
  sr: 44032 #int
  signal_base_dir_in: "C:/Users/luede/Seafile/WhaleFM"
  signal_base_dir_out: ""
  species_list: ["Northern_Right_Whale"] #used in tests
mfcc:
  tukey_alpha: 0.5 #float
  mfcc_frame_length: 0.025
  n_mfcc: 13
  hop_length: 0.01
  n_fft: 2048
  feature_set: ["mfcc","delta","delta2"] # mfcc with delta, or delta2, vggish is not implemented yet
loadDatabase:
  database_base_dir_in: ""
  database_base_dir_out: "C:/Users/luede/Downloads/export_whales_whaleFM"

svm:
  random_state: 42
  kernel: "rbf"
  model_dir_out: "C:/Users/luede/Documents/Github/whaledetection/models/svm"
  test_size: 0.2

rf:
  random_state: 42
  model_dir_out: "C:/Users/luede/Documents/Github/whaledetection/models/rf"
  test_size: 0.2
  estimators: 300

feature:
  feature_type: "mfcc"

experiment:
  output_dir: "results/cv/tmp"