swt:
  level: 4 #int
  swt_frame_length: 2 # int in seconds
  swt_hop_ratio: 0.5 #float
  axis: -1 # int
  k: 1.4826 #float
  wavelet: "db4" #str
  t_mode: "sure" #str
  t_meth: "soft" #str

denoise:
  method: "swt"
pad:
  pad_mode: "reflect" #str
  
loadSignal:
  sr: 44032 #int
  signal_base_dir_in: "C:/Users/luede/Seafile/WhaleData"
  signal_base_dir_out: ""
  species_list: ["Northern_Right_Whale"]
mfcc:
  tukey_alpha: 0.5 #float
  mfcc_frame_length: 0.025
  n_mfcc: 13
  hop_length: 0.01
  n_fft: 2048
  feature_set: ["mfcc"]
loadDatabase:
  database_base_dir_in: ""
  database_base_dir_out: "C:/Users/luede/Downloads/export_whales"

svm:
  random_state: 42
  kernel: "rbf"
  model_dir_out: "C:/Users/luede/Documents/Github/whaledetection/models/svm"
  test_size: 0.2

rf:
  random_state: 42
  model_dir_out: "C:/Users/luede/Documents/Github/whaledetection/models/rf"
  test_size: 0.2
  estimators: 300

feature:
  feature_type: "mfcc"
